@startuml
title Use Cases - Admin
left to right direction

actor Admin

Admin --> (UC-01: Register / Login / Logout)
Admin --> (UC-03: View Course Details)
Admin --> (UC-08: Approve Course Request / Instructor Approval)
Admin --> (UC-11: Create Course)
Admin --> (UC-13: View Reports / Analytics)
Admin --> (UC-14: Issue Certificate)
Admin --> (UC-16: Payment / Checkout)  
Admin --> (UC-17: Manage Users & Roles)
Admin --> (UC-18: Audit Log / System Logs)
Admin --> (UC-09: Send/Receive Notifications)

@enduml
