@startuml
title Use Cases - Instructor
left to right direction

actor Instructor

Instructor --> (UC-01: Register / Login / Logout)
Instructor --> (UC-03: View Course Details)
Instructor --> (UC-05: Learn Course / View Lesson)
Instructor --> (UC-07: Grade Assignment)
Instructor --> (UC-09: Send/Receive Notifications)
Instructor --> (UC-10: Messaging / Q&A)
Instructor --> (UC-11: Create Course)  
Instructor --> (UC-12: Modify Course)
Instructor --> (UC-13: View Reports / Analytics)
Instructor --> (UC-14: Issue Certificate)

@enduml
